source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.4.1"

gem "rails",           "~> 8.0"
gem "propshaft"
gem "importmap-rails", "~> 2.1"
gem "turbo-rails",     "~> 2.0"
gem "stimulus-rails",  "~> 1.3"
gem "jbuilder",        "~> 2.13"
gem "puma",            "~> 6.4"
gem "bootsnap",        "~> 1.18", require: false
gem "sqlite3",         "~> 2.1"

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  gem "web-console",         "~> 4.2"
  gem "solargraph",          "~> 0.56"
  gem "irb",                 "~> 1.14"
  gem "repl_type_completor", "~> 0.1"
end

group :test do
  gem "capybara",                 "~> 3.40"
  gem "selenium-webdriver",       "~> 4.27"
  gem "rails-controller-testing", "~> 1.0"
  gem "minitest",                 "~> 5.25"
  gem "minitest-reporters",       "~> 1.7"
  gem "guard",                    "~> 2.18"
  gem "guard-minitest",           "~> 2.4"
end

# Windows ではタイムゾーン情報用の tzinfo-data gem を含める必要があります
# gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
